backend:
  name: git-gateway
  branch: main # Certifique-se de que sua branch principal no GitHub se chama main

collections:
  - name: "cardapio"
    label: "Cardápio"
    folder: "data/cardapio" # Onde os produtos serão salvos como arquivos individuais
    create: true
    slug: "{{title}}"
    fields:
      - { label: "Nome do Produto", name: "title", widget: "string" }
      - { label: "Preço", name: "price", widget: "number", value_type: "float" }
      - { label: "Descrição", name: "description", widget: "text" }
      - { label: "Categoria", name: "category", widget: "select", options: ["Fritos", "Porções", "Bebidas", "Doces"] }
      - { label: "Imagem", name: "image", widget: "image", required: false }
